# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.TextField()),
                ('red', models.TextField()),
                ('localizador', models.TextField()),
                ('latitud', models.TextField()),
                ('longitud', models.TextField()),
                ('administrador', models.TextField()),
                ('canal', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estado', to='service.Estacion')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Historial', to='service.Estacion')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='historial',
            unique_together=set([('estacion', 'fecha')]),
        ),
        migrations.AlterUniqueTogether(
            name='estado',
            unique_together=set([('estacion', 'fecha')]),
        ),
    ]
