# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.TextField()),
                ('red', models.TextField()),
                ('localizador', models.TextField()),
                ('latitud', models.TextField()),
                ('longitud', models.TextField()),
                ('administrador', models.TextField()),
                ('canal', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('servidor', models.TextField()),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estacion13', to='service.Estacion')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Estado232',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('servidor', models.TextField()),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estacion232', to='service.Estacion')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Funcionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('servidor', models.TextField()),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionamiento', to='service.Estacion')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Funcionamiento_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('servidor', models.TextField()),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionamiento_temp', to='service.Estacion')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField()),
                ('servidor', models.TextField()),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Historial', to='service.Estacion')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='historial',
            unique_together=set([('estacion', 'fecha')]),
        ),
        migrations.AlterUniqueTogether(
            name='funcionamiento_temp',
            unique_together=set([('estacion', 'fecha')]),
        ),
        migrations.AlterUniqueTogether(
            name='funcionamiento',
            unique_together=set([('estacion', 'fecha')]),
        ),
        migrations.AlterUniqueTogether(
            name='estado232',
            unique_together=set([('estacion', 'fecha')]),
        ),
        migrations.AlterUniqueTogether(
            name='estado13',
            unique_together=set([('estacion', 'fecha')]),
        ),
    ]
